/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeaderboardEntry = IDL.Record({
  'moduleId' : IDL.Text,
  'moduleName' : IDL.Text,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : IDL.Int,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearAllResults' : IDL.Func([], [], []),
  'getAllGameResults' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getResultsByModule' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'saveGameResult' : IDL.Func([LeaderboardEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeaderboardEntry = IDL.Record({
    'moduleId' : IDL.Text,
    'moduleName' : IDL.Text,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : IDL.Int,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    'clearAllResults' : IDL.Func([], [], []),
    'getAllGameResults' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getResultsByModule' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'saveGameResult' : IDL.Func([LeaderboardEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };